version: '3.8'

services:
  nginx:
    container_name: lgtm-cat-api-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 3331:3331
    environment:
      - BACKEND_HOST=lgtm-cat-api-dev
      - PORT=3331
    depends_on:
      - dev
    networks:
      - lgtm-cat
  dev:
    container_name: lgtm-cat-api-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./:/go/app
    command: air -c ${AIR_CONF}
    ports:
      - 3333:3333
      - 2345:2345
    environment:
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - lgtm-cat
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: unit-test
    volumes:
      - ./:/go/app
    command: go test -shuffle=on -v ./...
    environment:
      TEST_DB_HOST: ${TEST_DB_HOST}
      TEST_DB_USER: ${TEST_DB_USER}
      TEST_DB_PASSWORD: ${TEST_DB_PASSWORD}
      TEST_DB_NAME: ${TEST_DB_NAME}
    networks:
      - lgtm-cat
networks:
  lgtm-cat:
    external: true
