// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type LgtmImage struct {
	ID int32
	// 画像ファイル名になっているuniqueな文字列が格納される .e.g. aaaaaaaa-aaaa-aaaa-aaaa-123456788qqq
	Filename string
	// S3に保存されているパス .e.g. YYYY/MM/DD/HH
	Path      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
