name: ci
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.44.2
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: checkout
        uses: actions/checkout@v3
      - name: checkout migration repo
        uses: actions/checkout@v3
        with:
          repository: nekochans/lgtm-cat-migration
          path: lgtm-cat-migration
      - name: docker-compose up
        working-directory: ./lgtm-cat-migration
        run: docker-compose up --build -d
      - name: install dependencies
        run: |
          go mod download
      - name: run unit tests
        run: |
          go test -v ./usecase/createltgmimage
